# Generated by Django 3.0.6 on 2020-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_author',
            field=models.TextField(blank=True),
        ),
    ]
