# Generated by Django 3.0.6 on 2020-06-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200610_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url',
            new_name='script',
        ),
    ]
