# Generated by Django 3.0.6 on 2020-06-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200611_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='script',
        ),
    ]
