# Generated by Django 3.0.6 on 2020-06-03 07:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to=blog.models.upload_location),
        ),
        migrations.DeleteModel(
            name='PostDraft',
        ),
    ]
