# Generated by Django 3.0.6 on 2020-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200603_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_draft',
            field=models.CharField(default='checked', max_length=150),
        ),
    ]
