# Generated by Django 3.0.6 on 2020-06-03 15:29

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200603_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='staticfiles/images/logo2.PNG', upload_to=blog.models.upload_location),
        ),
    ]
