# Generated by Django 3.0.6 on 2020-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='story_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='story_title',
            field=models.CharField(blank=True, default='My story in Pictures', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='My Pic', max_length=255, null=True),
        ),
    ]
