# Generated by Django 3.0.6 on 2020-06-20 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_auto_20200619_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='story_content',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='story_title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.CreateModel(
            name='PhotoStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(blank=True, default='My story in Pictures', max_length=255, null=True)),
                ('story_content', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photo_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_photo', to='blog.PhotoStory'),
        ),
    ]
