# Generated by Django 3.0.6 on 2020-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200620_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='describe_the_picture',
            field=models.CharField(blank=True, default='Describe the Pic', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_of_picture',
            field=models.CharField(blank=True, default='Title of the Pic', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photostory',
            name='story_content',
            field=models.TextField(blank=True, default='Write your Story', null=True),
        ),
        migrations.AlterField(
            model_name='photostory',
            name='story_title',
            field=models.CharField(blank=True, default='Title of your Story', max_length=255, null=True),
        ),
    ]
