# Generated by Django 3.0.6 on 2020-06-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200620_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title_of_picture',
            new_name='title_of_the_picture',
        ),
    ]
