# Generated by Django 3.0.6 on 2020-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200620_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photostory',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='photostory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
