# Generated by Django 3.0.6 on 2020-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200624_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='describe_the_picture',
            field=models.CharField(blank=True, default='Describe the Pic/Video', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title_of_the_picture',
            field=models.CharField(blank=True, default='Title of the Pic/Video', max_length=255, null=True),
        ),
    ]
