# Generated by Django 3.0.6 on 2021-05-08 07:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200627_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='key_point',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.pic_loc),
        ),
    ]
