# Generated by Django 3.0.6 on 2021-08-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210508_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_file_link',
            field=models.CharField(blank=True, help_text='Your image/video file link. Enter only one link. Enter only if notuploading a file', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='key_point',
            field=models.BooleanField(default=True, verbose_name='Show key points'),
        ),
    ]
