# Generated by Django 3.0.6 on 2021-08-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210829_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file_link',
        ),
    ]
