# Generated by Django 3.0.6 on 2021-08-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210830_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
